# Generated by Django 2.2.7 on 2020-01-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191117_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='genre',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], default='Female', max_length=140),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='pays',
            field=models.CharField(choices=[('CMR', 'Cameroun')], default='CMR', max_length=140),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='profession',
            field=models.CharField(choices=[('AGR', 'Agriculteur'), ('ETU', 'Etudiant'), ('MEN', 'Menagere'), ('OUV', 'Ouvrier')], default='MEN', max_length=140),
        ),
        migrations.AlterField(
            model_name='adresse',
            name='region',
            field=models.CharField(choices=[('Adamaoua', 'adamaoua'), ('Centre', 'centre'), ('Est', 'est'), ('Extreme-Nord', 'extreme nord'), ('Littoral', 'littoral'), ('Nord', 'nord'), ('Nord-Ouest', 'nord ouest'), ('Ouest', 'ouest'), ('Sud', 'sud'), ('Sud-Ouest', 'sud ouest')], default='Adamaoua', max_length=140),
        ),
    ]
